
[CreatBot_F430NX]
versions = 1.0, 1.1
#V1.1 Add door detection; Add eddy;

[CreatBot_D600Pro2HS]
versions = 1.0, 1.1
#V1.1 Add door detection

[CreatBot_D600Pro2HS_KIT]
versions = 1.0

[CreatBot_D600Pro3HS]
versions = 1.0

[CreatBot_D1000HS]
versions = 1.0, 1.1
#V1.1 Add door detection

[CreatBot_D1000HS_KIT]
versions = 1.0

[CreatBot_D1000ProHS]
versions = 1.0, 1.1
# V1.0: 2 Z axes
# V1.1: Add support for 4 Z axes

[CreatBot_P800]
versions = 1.0
